version: "3"

services: 
  app:
    image: node:12-alpine
    user: "node"
    working_dir: /home/node/server
    environment:
       VIRTUAL_HOST: rysapp.com
       LETSENCRYPT_HOST: rysapp.com
       LETSENCRYPT_EMAIL: admin@rysapp.com
       NODE_ENV: production     
    volumes:
      - ./site:/home/node/server
    expose:
      - "3000"
    restart: always
    command: "npm start"
    container_name: rys_app

networks:
  default:
    external:
      name: nginx-proxy